# Generated by Django 5.2.8 on 2025-12-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cartitem_user_historialcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('manga', 'Manga'), ('ln', 'Light Novel'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua')], default='manga', max_length=20),
        ),
    ]
