# Generated by Django 5.2.8 on 2025-12-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('demography', 'Demografía'), ('genre', 'Género')], default='demography', max_length=20),
        ),
    ]
